package com.HanFeng.service

object VpnConstants {
    const val LOCAL_DNS_V4 = "10.99.0.2"
    const val LOCAL_DNS_V6 = "fd66:66::2"
    const val STALE_CACHE_GRACE_MILLIS = 60_000L
    const val DNS_SERVER_CACHE_TTL_MILLIS = 15_000L
    const val ROUTE_CACHE_PRUNE_INTERVAL_MILLIS = 60_000L

    const val DNS_RESPONSE_CACHE_MAX_SIZE = 4096
    const val DECISION_LOG_CACHE_MAX_SIZE = 256
    const val AD_IP_TARGET_CACHE_MAX_SIZE = 1024
    const val HTTP_DECRYPT_IP_CACHE_MAX_SIZE = 512
    const val HTTPS_DECRYPT_IP_CACHE_MAX_SIZE = 512
    const val QUIC_ROUTE_CACHE_MAX_SIZE = 1024
    const val HTTPS_PROXY_FLOW_CACHE_MAX_SIZE = 256
    const val HTTPS_BRIDGE_SOCKET_CACHE_MAX_SIZE = 128
    const val LOCAL_PROXY_TCP_FLOW_CACHE_MAX_SIZE = 256
    const val LOCAL_PROXY_BRIDGE_SOCKET_CACHE_MAX_SIZE = 128
    const val PASSTHROUGH_TCP_FLOW_CACHE_MAX_SIZE = 512
    const val PASSTHROUGH_TCP_SOCKET_CACHE_MAX_SIZE = 256
    const val PASSTHROUGH_UDP_SESSION_CACHE_MAX_SIZE = 256

    const val APP_NAME_CACHE_MAX_SIZE = 256
    const val APP_NAME_CACHE_CONCURRENCY = 256
    const val DOMAIN_APP_CACHE_MAX_SIZE = 256
    const val SOURCE_PORT_APP_CACHE_MAX_SIZE = 256
    const val OWNER_UID_CACHE_MAX_SIZE = 512
    const val OWNER_UID_FAILURE_CACHE_MAX_SIZE = 512
    const val APP_LABEL_CACHE_MAX_SIZE = 128
    const val VENDOR_HINT_CACHE_MAX_SIZE = 512
    const val LOCAL_PROXY_TARGET_APP_CACHE_MAX_SIZE = 512
    const val DNS_SOCKET_POOL_MAX_SIZE = 4

    const val DNS_ASYNC_TASK_QUEUE_CAPACITY = 512
    const val DNS_ASYNC_RESULT_QUEUE_CAPACITY = 512
}
